name: Build

on:
  push:
    branches:
      - 'master'
    paths:
      - src/**
  schedule:
    - cron:  '0 0 1 * *'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Packages
      shell: bash
      run: |
        sudo apt-get install -y build-essential libspdlog-dev cmake qtbase5-dev libgl-dev
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -G "CodeBlocks - Unix Makefiles" .
        cmake --build . --target lilDevil -- -j 2
